# Generated by Django 3.2 on 2021-09-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_owner',
            new_name='is_psychologist',
        ),
    ]
