# Generated by Django 3.2 on 2021-09-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
