# Generated by Django 3.2 on 2021-09-14 02:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_psychologist_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='specialization',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('general_psychologist', 'общий психолог'), ('family_psychologist', 'семейный психолог'), ('children_psychologist', 'детский психолог'), ('clinical_psychologist', 'клинический психолог'), ('social_psychologist', 'cоциальный психолог'), ('corporate_psychologist', 'корпоративный психолог'), ('psychoanalyst', 'психоаналитик')], default='general_psychologist', max_length=50),
        ),
    ]
