# Generated by Django 3.2 on 2021-09-14 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0004_alter_psychologist_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'консультация назначена'), ('canceled', 'консультация отменена'), ('finished', 'консультация завершена')], default='booked', max_length=20)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_online', models.PositiveSmallIntegerField(default=1)),
                ('hours_offline', models.PositiveSmallIntegerField(default=1)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='appointment.appointment')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_items', to='psychologists.psychologist')),
            ],
            options={
                'db_table': 'appointment_items',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='psychologist',
            field=models.ManyToManyField(through='appointment.AppointmentItem', to='psychologists.Psychologist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
