# Generated by Django 3.2 on 2021-09-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('in process', 'запись в обработке'), ('booked', 'консультация назначена'), ('canceled', 'консультация отменена'), ('finished', 'консультация завершена')], default='booked', max_length=20),
        ),
    ]
